run:
  timeout: 5m

linters:
  disable:
    # Temporarily disabled - TODO: Fix these issues
    - errcheck      # Many unchecked errors to fix
    - unused        # Some unused code to clean up
    - gosimple      # Some simplification suggestions
    - ineffassign   # Some ineffectual assignments  
    - staticcheck   # Some staticcheck warnings

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
